#! /bin/bash

NOTES_VERSION="0.3"
NOTES_BINARY_NAME="notes"
NOTES_LOCATION="$HOME/.notes"

EDITOR="${EDITOR:-vim}"

# same as pass is doing
# notes group/subject
# notes subject

# notes somename
R="$(tput bold)$(tput setaf 1)"
G="$(tput bold)$(tput setaf 2)"
B="$(tput bold)$(tput setaf 4)"
W="$(tput bold)$(tput setaf 7)"
Y="$(tput bold)$(tput setaf 3)"
y="$(tput setaf 3)"
g="$(tput setaf 2)"
N="$(tput sgr0)"

template(){
	local note=$1

cat << EOF
DATE: $(date)
SUBJECT: $note
STATUS: STARTED
LAST EDIT: $(date)
COMMENT:
---

# vim: ft=notes
EOF
}

info(){
	local i="$1"
	case $i in
		-m ) printf "%s\n" "$2" ;;
		-e ) printf "%s\n" " ${R}* Error${N}: $2"; exit 254 ;;
		-w ) printf "%s\n" " ${Y}*${N}  $2" 	;; 
		-i ) printf "%s\n" " ${G}*${N}  $2" 	;; 
	esac

}

add_note(){
	local arg=${1##*/}
	local tips=0
	
	case $arg in
		--tips | -t ) tips=1; shift; note=${1##*/} ;;
		* ) note=${1##*/} 
	esac
	
	local path=$NOTES_LOCATION/$(dirname $1)
	
	# check if path exist
	[[ -f $path/$note ]] && info -e "${B}$path/${G}$note${N} exist, use edit or del!!"
	
	mkdir -p $path
	(( $tips )) && echo "# vim: ft=notes" > $path/$note || \
		template $note >  $path/$note
	
	$EDITOR $path/$note

}

edit_note(){
	local note=${1##*/}
	local path=$NOTES_LOCATION/$(dirname $1)

	[[ ! -f $path/$note ]] && info -e "note: ${B}$path/${G}$note${N} doesn't exist, use add!!"

	# set edit time
	sed -i "s/LAST EDIT:.*/LAST EDIT: $(date)/" $path/$note
	
	$EDITOR $path/$note

}

del_note(){
	local note=${1##*/}
	local path=$NOTES_LOCATION/$(dirname $1)

	[[ ! -f $path/$note ]] && info -e "Can't delete note: ${B}$path/${G}$note${N} doesn't exist!!"

	[[ $(find $path -type f | wc -l ) -gt 1 ]] && rm $path/$note || rm $path/$note && rmdir -p $path 2>/dev/null
	
	info -i "Removed ${B}$path/${G}$note${N}"

}

list_note(){
	local arg=${1}
	local treeopt

	case $arg in
		-d | --dir ) treeopt='-d'; shift; note=${1};;
		* ) note=${1} ;;
	esac

	info -m "Notes Store:"
	[[ -z $note ]] && tree -C -l $treeopt --noreport $NOTES_LOCATION | tail -n +2 || \
		(info -m "${B}$note:${N}"; tree -C -l --noreport $NOTES_LOCATION/$note | tail -n +2)

}

[[ $# -lt 1 ]] && list_note && exit

case $1 in
	add | a ) add_note ${@:2} ;;
 edit | e ) edit_note ${@:2} ;;
 del | rm ) del_note ${@:2} ;;
	 ls | l ) list_note ${@:2} ;;
	 * ) [[ ${@:1} =~  \-[a-zA-Z0-9] ]] && \
			 info -e "Not recognized: ${@:1}" 
			 edit_note ${@:1} ;;
esac
